export const EVENT_ACTIONS = {
  SET_EVENTS: 'SET_EVENTS',
  APPEND_EVENTS: 'APPEND_EVENTS',
  SET_MY_EVENTS: 'SET_MY_EVENTS',
  SET_JOINED_EVENTS: 'SET_JOINED_EVENTS',
  SET_SAVED_EVENTS: 'SET_SAVED_EVENTS',
  SET_LOADING: 'SET_LOADING',
  SET_HAS_MORE: 'SET_HAS_MORE',
  SET_FILTERS: 'SET_FILTERS',
  UPDATE_EVENT: 'UPDATE_EVENT',
  RESET: 'RESET',
};

export const COMMUNITY_ACTIONS = {
  SET_COMMUNITIES: 'SET_COMMUNITIES',
  SET_JOINED: 'SET_JOINED',
  SET_ACTIVE: 'SET_ACTIVE',
  SET_POSTS: 'SET_POSTS',
  SET_LOADING: 'SET_LOADING',
  UPDATE_POST: 'UPDATE_POST',
  RESET: 'RESET',
};

export const MARKET_ACTIONS = {
  SET_LISTINGS: 'SET_LISTINGS',
  APPEND_LISTINGS: 'APPEND_LISTINGS',
  SET_MY_LISTINGS: 'SET_MY_LISTINGS',
  SET_SAVED: 'SET_SAVED',
  SET_LOADING: 'SET_LOADING',
  SET_HAS_MORE: 'SET_HAS_MORE',
  SET_FILTERS: 'SET_FILTERS',
  UPDATE_LISTING: 'UPDATE_LISTING',
  RESET: 'RESET',
};
